
name: Test

on:
  workflow_dispatch:
  push:
    tags:
      - v*
    branches:
      - main

permissions:
  contents: read

jobs:
  test-deploy-preview:
    name: Test deploy preview site
    runs-on: ubuntu-latest
    environment:
      name: test-preview
      url: ${{ steps.deploy.outputs.netlify-deploy-url }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test deploy preview site
        id: deploy
        uses: ./
        with:
          auth-token: '${{ secrets.NETLIFY_AUTH_TOKEN }}'
          site: '${{ vars.NETLIFY_SITE_NAME }}'
          dir: sites/preview
          alias: preview

  test-deploy-prod:
    name: Test deploy production site
    runs-on: ubuntu-latest
    if: always()
    environment:
      name: test-prod
      url: ${{ steps.deploy.outputs.netlify-deploy-url }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test deploy production site
        id: deploy
        uses: ./
        with:
          auth-token: '${{ secrets.NETLIFY_AUTH_TOKEN }}'
          site: '${{ vars.NETLIFY_SITE_NAME }}'
          dir: sites/prod
          prod: true
